### ISSUE TITLE
Search typing issue

### ISSUE THREAD

**Issue by Nail757** [typora/typora-issues#1005]
As I press Ctrl+F and start typing while editing a big text, every letter I type initiates search routine which causes app hanging up for a while. It takes especially long time for the first letter as the program tries to find and mark every such letter in the text. 
I suppose there should be at least an option to perform search when I press Enter only. Otherwise the search should be more CPU-friendly. Or probably have some timer until initiation, so that it only starts as I stop typing the whole word.
My system is Windows 10 x64, Typora v0.9.37

Thanks for great app, btw!

**Comment by majikang** [comment]
me too and very slow when searching

**Comment by aladagemre** [comment]
Hi, #1005 and #1007 are redirecting to each other and both are closed. Are you tracking this issue somewhere else? I love Typora but this is the single major pain I'm having.

**Comment by aladagemre** [comment]
I love Typora but this is the single major pain I'm having with Typora. I'd love to see it fixed. (Deleted my previous comment, I misread the issue).

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by Nail757** [comment]
Can't confirm fix. Version 0.9.57 still hangs up for several minutes when searching a 3-letter word in a 58K-words file. Seems to behave so only with common words (appear many times in the text).

**Comment by brikis98** [comment]
Same issue here on Typora Version 0.9.9.21.1 (1913) on Mac. The editor is fantastic and I've switched to it for all my note taking, but search clearly has a bug. I hit `CMD + F`, type a letter or two, and then Typora hangs for 5-15 seconds before I can type anything else. I'm on a 2.9Ghz Core i9 with 32GB of RAM, so I'm guessing this is a bug in the way the algorithm does search or, more likely, highlighting. 

@abnerlee Should we file a new bug or should this one be re-opened?

**Comment by abnerlee** [comment]
This is in #2107
