### ISSUE TITLE
Shortcut for Delete Row

### ISSUE THREAD

**Issue by elbaro** [typora/typora-issues#1087]
According to http://support.typora.io/Table-Editing/ , table row delete is done by `ctrl+shift+L` but this shortcut is not registered by default on my linux.

Also I cannot bind 'ctrl+shift+L' to 'Delete Line'. it binds well to 'Strong' so this is not a shortcut conflict.

```
"keyBinding": {
    // for example:
    // "Always On Top": "Ctrl+Shift+P"
    "Delete Line": "Ctrl+Shift+L", // not working
    // "Strong": "Ctrl+Shift+L" // works
  },
```

**Comment by abnerlee** [comment]
see https://github.com/typora/typora-issues/issues/1087

**Comment by elbaro** [comment]
This is #1087.

**Comment by abnerlee** [comment]
https://github.com/typora/typora-issues/issues/753

**Comment by elbaro** [comment]
Thanks. After reset, `Ctrl+Shift+L` is bound to `Delete Line` but the function doesn't work.

I manually mouse-clicked `Edit>Delete Range>Delete Line` and it doesn't delete the current line or table row. So this is not a shortcut issue anymore.

`Delete Word` and `Delete Styled Scope` works.

**Comment by abnerlee** [comment]
should be fixed, please check updates

**Comment by bhuesemann** [comment]
Not fixed for me. Seems to be conflict with hide menu/navigation on the left. Override in keybinding json doesn't work either. I've tried both 
"Delete Line": "Ctrl+Shift+L", 
"Delete Line/Sentence": "Ctrl+Shift+L"

Both are not working.

Version: 0.9.62 beta
Plattform Windows

**Comment by abnerlee** [comment]
Default shortcut keys for Delete Line is removed, please make a custom key binding. 
In table `Ctrl + Shift + Backspace` can be used for delete row. (https://support.typora.io/Shortcut-Keys/#edit)

**Comment by phillijw** [comment]
Ctrl + Shift + Backspace does't work for me.

Why does this have to be difficult? What do I have to do to have a shortcut that deletes a table row?
