### ISSUE TITLE
Window control buttons not properly aligned when maximized in unibody style

### ISSUE THREAD

**Issue by gooeye** [typora/typora-issues#1186]
Image of issue: ![image](https://user-images.githubusercontent.com/32929088/35432364-c419c6fa-02ba-11e8-8eb2-da2eb63d76e6.png)

As can be seen in the image above, the restore button appears to be slightly larger in height and length, compared to the other buttons. While the misalignment is not visible under normal circumstance, it can be seen when the buttons are hovered over:
![image](https://user-images.githubusercontent.com/32929088/35433112-30017b0e-02bd-11e8-879d-2e0fc94fb868.png)

This issue only occurs while the Typora window is maximized. This could be due to the restore button using SVG for its icon while the close and minimize buttons use unicode characters inserted with the css selector `:before` for icons.
![image](https://user-images.githubusercontent.com/32929088/35432654-afd285f0-02bb-11e8-88d7-082f3a1cb693.png)

OS: Windows 7 Ultimate
Typora Version: 0.9.42 (beta)

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by movitecc** [comment]
if typora linux 0.9.96 deb dont support unibody window style , default mode is classic.

**Comment by Dosochka** [comment]
I have 0.9.98 version (Windows) and bug still presents

![image](https://user-images.githubusercontent.com/67841399/113712674-16467b00-96ef-11eb-9bef-41903e8083e4.png)

**Comment by abnerlee** [comment]
Are you using built-in themes?

**Comment by Dosochka** [comment]
Yes. It is the default "Night" theme with different colors. After reinstall 0.10.3 (to be clear that it wasn't from me) it still presents. 
![image](https://user-images.githubusercontent.com/67841399/116205514-840e2180-a746-11eb-9cb0-a6d2a2c2c367.png)
Screenshot of not modified theme.
