### ISSUE TITLE
Please make your markdown table prettifying logic optional and off by default

### ISSUE THREAD

**Issue by KirkMunro** [typora/typora-issues#1189]
Today if I take markdown documentation written in other tools (and managed in some source control system) and edit it with Typora, I get many, many unwanted changes to the markdown tables. For example, consider this simple markdown table:

```markdown
|Text|Associated author|
|--|--:|
|One fish|Dr. Seuss|
|Gryffindor|J. K. Rowling|
```

## Issue 1

If I open the document in Typora, and switch the view to source code mode, what Typora shows me as the markdown source behind my table is incorrect. It's showing me prettified markdown, and if I close the file it closes properly as I didn't modify it, but the file contents it is displaying are wrong. It should display the actual contents of the unprettified file. Prettification is only needed for rendered content, never, ever for raw markdown, and users must be able to know that what they are looking at in the source code mode (raw markdown mode) is the actual markdown, and nothing else.

## Issue 2

If I open the document in Typora, make a change anywhere else in the file, and then save my file I get not only the changes I made but also unwanted prettification of all tables I had in the file. This should never happen, at least not by default.

## Issue 3

If my table has any justification on any of the columns, the prettification logic justifies the raw content in markdown as well. That creates a maintenance headache if you ever want to change the justification on a table column in any tool other than Typora. These non-standard, unwanted behaviors are absolutely deal breakers for team adoption of tools, because they force an all or none switch, and your tool isn't ever going to be comprehensive enough to fit into the all category.

I can go on, but I really wanted to make it clear why the prettification of markdown in this tool has to be undone. Personally I wouldn't even recommend it be optional, without warning. Focus on being the best markdown renderer/editor out there by adhering to markdown standards, following markdown best practices, and making the rendering/editing experience WYSIWYG in a single window the best there is without your users having to go in and turn on/off a bunch of options (like the strict GFM settings that are actually related to the CommonMark standard), and you'll have a much better chance of success IMHO.

**Comment by AlexPasternak** [comment]
Hmm, I didn't realize the tool did that (I don't do much with tables). Agreed that pasting in the raw MD, then just switching back and forth out of source mode shouldn't affect your content like this. I didn't make any content changes, yet the file is completely different now.

![2018-01-26 12 50 27](https://user-images.githubusercontent.com/1819485/35453296-ac380a88-0297-11e8-8d32-c730a6d10839.gif)

**Comment by vassudanagunta** [comment]
I think making Typora play nice with other tools and collaborative work contexts (e.g. open source, teams) is more important than adding new features. But new features keep getting added before getting the core solid, with a clear coherent philosophy.

**Comment by abnerlee** [comment]
We will use following behavior:

- Do not change text/code for existing table.
- Reformat table when user paste table into hybrid mode.
- When user edit a table. If its source code is originally "aligned", we will prettify it
  If not, try apply the text change in cell, add row/row following existing style.

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by cycychenyi** [comment]
@abnerlee hi, I still can't find the option to disable table prettifying on Typora version 0.11.13(beta).

**Comment by RobertBromfield** [comment]
To follow on what @cycychenyi comment this still doesn't seem to be a feature 

While I personally have no opinion on which it should be surely it should follow the style of what it already was if a cell is changed.

It seems bizarre to have the entire table be in the diff if you simply add a row to it.
