### ISSUE TITLE
Shortcut to format code behave incorrectly in list

### ISSUE THREAD

**Issue by ThomasAuriel** [typora/typora-issues#1348]
The shortcut to turn a text format in code format does not behave correctly when it is apply at the end of a list element.

For instance in the following list:

```markdown
- element1
- element2
- element3
```

I want turn the element2 in code for format:

```markdown
- element1
- `element2`
- element3
```

But if I place the cursor on the element2 and apply the shortcut for code (in my configuration it is `Crtl+Shift+ù`), then this append:

```markdown
- element1
- `element2
- element3
```

And it's display as following:

```markdown
- element1
- `element2
- `element3
```

If I select the element2 and then apply the shortcut, I have the correct behaviour.

**Comment by abnerlee** [comment]
Typora/OS version?

**Comment by abnerlee** [comment]
Cannot reproduce.

Please add Typora/OS version and ways to reproduce.

**Comment by ThomasAuriel** [comment]
Typora version: 0.9.44
OS: Windows 7 Professional

**Comment by ThomasAuriel** [comment]
**This happen also with other text format shortcut.**

For instance with bold shortcut I get:
```
- an element1
- an element2
- an **element3
- **an element4
- an element5
```

**It happens also in sentence.**

For instance if a want to turn a text in bold text. If i place the cursor just after the targeted world I get:
```
This is a simple **element**.
I this case i did want to turn bold the world "simple" instance of element.
```

**Comment by abnerlee** [comment]
Could you update to latest version?

**Comment by ThomasAuriel** [comment]
I did. It seems that still happening but in a slight different way.
Now, the list appears as:

```
- element1
- element2
- `element3`
```
While i want to change `element2`.

**Comment by abnerlee** [comment]
It seems I cannot reproduce this, could you confirm it on v0.9.47?

**Comment by ThomasAuriel** [comment]
Ok I reinstalled it.
**It fixed the issue.**
That's really wired. I guess an update broke something ...

**Comment by ThomasAuriel** [comment]
Their is still the issue with end of line:

![image](https://user-images.githubusercontent.com/4946109/38016476-61835b84-326f-11e8-8e7a-34b14eb7e1fd.png)
give the result:
![image](https://user-images.githubusercontent.com/4946109/38016490-71e8d01c-326f-11e8-9b0c-a928cb9cc4b4.png)

And I use a refreshly downloaded and installed Typora editor:
![image](https://user-images.githubusercontent.com/4946109/38016538-9168baf6-326f-11e8-8205-aeb6976c14de.png)

**Comment by abnerlee** [comment]
I see, I can reproduce this by putting the caret at end of line

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by ThomasAuriel** [comment]
It appears that the issue is partially solved.

I took this example:
![image](https://user-images.githubusercontent.com/4946109/38235393-54583702-3721-11e8-83ec-5aff6165e209.png)
(please, note the dot missing in the first line but not on others)

So for the first line, the behaviour is now correct:
![image](https://user-images.githubusercontent.com/4946109/38235434-7a04509e-3721-11e8-93a5-46169db6e193.png)

But for the second line, it is still uncorrect, presumably due to the dot:
![image](https://user-images.githubusercontent.com/4946109/38235486-a46bb25a-3721-11e8-8208-b87596fec7c1.png)
I placed the caret between the last word and the second line dot.
This code fence are present in the code source but not yet rendered. If I modify the third line, the correct format appear immedialty.

If a placed the carret at the end of the word and apply the code format, the next word is took in consideration instead of the targeted one. In the next example, I placed the caret after the word Example:
![image](https://user-images.githubusercontent.com/4946109/38235683-427290fe-3722-11e8-94f2-88195264b884.png)

Btw, that really a minor issue. It does not degrade my experience of the software, which is very good!

**Comment by abnerlee** [comment]
Should be fixed in new release
