### ISSUE TITLE
Sequence Diagram not rendered correctly

### ISSUE THREAD

**Issue by raytangRT** [typora/typora-issues#1465]
Typora version 0.9.94 (Beta)

1. Actor duplicated when participant is declared
2. Manually activate and deactivate actor cause the sequence diagram not rendering .

![2018-05-03 08_51_48-untitled - typora](https://user-images.githubusercontent.com/30689714/39555959-7482775e-4eaf-11e8-8a0a-50b8fcc1ef14.png)

3. editor can not use when after opening the bugged diagram
![3](https://user-images.githubusercontent.com/30689714/39556046-04c28d54-4eb0-11e8-9f31-7a0c476bcc8c.gif)

```Mermaid
sequenceDiagram
    participant j as John
    participant Alice
    
    Alice->>j: Hello John, how are you?
    activate j
    j-->>Alice: Great!
    deactivate j
```

**Comment by raytangRT** [comment]
sample attached.

**Comment by abnerlee** [comment]
same reason as  https://github.com/typora/typora-issues/issues/1467

Fixed in new release

**Comment by raytangRT** [comment]
Hi @abnerlee, I tried version 0.9.5 (beta), but Problem 1 & 2 still persist, can you take a look at it?

1. Actor duplicated when participant is declared

```Mermaid
sequenceDiagram
    participant John
    participant Alice
    
    Alice->>John: Hello John, how are you?
    activate John
    John-->>Alice: Great!
    deactivate John
```
![2018-05-04 08_49_46-untitled - typora](https://user-images.githubusercontent.com/30689714/39609025-3fee17f4-4f78-11e8-9bd6-01cc006e28cf.png)

2. Manually activate and deactivate actor cause the sequence diagram not rendering .

```mermaid
sequenceDiagram
    Alice->>John: Hello John, how are you?
    activate John
    John-->>Alice: Great!
    deactivate John
```
![3](https://user-images.githubusercontent.com/30689714/39609080-bd86b928-4f78-11e8-91d6-b48e7283738f.gif)

**Comment by abnerlee** [comment]
@raytangRT What's your OS? Are you on Windows 7?

**Comment by abnerlee** [comment]
You could hot fix this by using LF (instead of CRLF) as default line ending (can be set from menu bar)

**Comment by raytangRT** [comment]
@abnerlee thanks, I tried you fix and the sequence diagram is showing.

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by JPOstholt** [comment]
Hi, I'm using version 0.9.9.24.2 (2386) and the issue still exists:

![image](https://user-images.githubusercontent.com/20239706/56579710-1ec04c80-65d1-11e9-947f-bd9f4846aa8e.png)

**Comment by abnerlee** [comment]
@JPOstholt could you paste the mermaid code?
