### ISSUE TITLE
Error with reading exported PDF

### ISSUE THREAD

**Issue by zofia1410** [typora/typora-issues#1563]
There is some problem with reading exported PDF. When I open pdf file in Adobe Acrobat I receive this error: 
<img width="538" alt="zrzut ekranu 2018-06-16 o 22 43 01" src="https://user-images.githubusercontent.com/26409634/41502312-78f01af0-71b7-11e8-9680-8b87d00dc76a.png">
**Translation**: There was a problem reading this document (14).

Another issue is that, I do not have in this exported document first page of it. Instead of my beginning content of my file I have small square _page_.

The bug is difficult to reproduce, but it appears almost every time. It does not matter, if I create my own theme or use one of a default theme.

macOS High Sierra 10.13.5, Typora version 0.9.9.16.2 (0.9.9.16.2)

**Comment by abnerlee** [comment]
Can the output PDF be opened by Preview.app?

Also, could you send us (<hi@typora.io>) a sample file that can reproduce this?

**Comment by xelzmm** [comment]
Hello I can reproduce this issue.

Version : 0.9.9.15.3 (0.9.9.15.3)
I've attached an archive which contains a demo `test.md` and exported pdf file.

[test.zip](https://github.com/typora/typora-issues/files/2330608/test.zip)

when open the pdf file with Adobe Acrobat Reader DC(version 2018.011.20058) on Windows 10 Home Edition, I got this:

![adobereader](https://user-images.githubusercontent.com/1187900/44764302-a3151980-ab81-11e8-9df2-32b5be543e6d.png)

> There was a problem reading this document (14)

![adobereader2](https://user-images.githubusercontent.com/1187900/44764307-a7d9cd80-ab81-11e8-9272-b6c48ae23656.png)

I think the mac version of Adobe Acrobat Reader would fail, too.

I've tried Preview.app, Safari.app, Chrome on Mac OSX, Chrome on Windows, MSIE Edge, Foxit pdf reader on Linux, iPhone Preview and many other application in multiple platforms, everything works fine.

**Comment by abnerlee** [comment]
> I've tried Preview.app, Safari.app, Chrome on Mac OSX, Chrome on Windows, MSIE Edge, Foxit pdf reader on Linux, iPhone Preview and many other application in multiple platforms, everything works fine.

You mean other apps can view the PDF except Adobe Acrobat Reader?

**Comment by xelzmm** [comment]
Yes, exactly.
For my case, Adobe Acrobat Reader can only render few pages in the pdf, pretty well, leaving other pages blank and even without correct page size.
For the demo `test.zip` I've attached above, there is only one page so that Adobe Acrobat Reader shows nothing.

![adobereader3](https://user-images.githubusercontent.com/1187900/44770334-525dea80-ab9a-11e8-8104-33f31c0dae5b.png)

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by xelzmm** [comment]
Nice work！

> Fixed in new release

**Comment by LHS1998** [comment]
The problem still exist!
[typroa-issue.zip](https://github.com/typora/typora-issues/files/2730385/typroa-issue.zip)

**Comment by LHS1998** [comment]
With this case, 
Device: Mac Book Pro 2017, 13-inch
System: 10.13.4 (17E199)
Typora: 0.9.9.19.4 (1355)
Theme: Academic
