### ISSUE TITLE
regression: URL drag n drop from Safari address bar inserts clipboard, not link

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#1612]
[Desired behavior](https://github.com/typora/typora-issues/issues/1073#issuecomment-347567672) was intruduced on May 1st (#899, #1073). But after a recent update, dragging the URL from the address bar inserts whatever is in the clipboard rather than a markdown link with the URL and page title.

**Comment by abnerlee** [comment]
I'm not able to reproduce this. 

What's your macOS/Safari version, and from which webpage will this bug occur?

**Comment by vassudanagunta** [comment]
@abnerlee  Not fixed. Please re-open this issue.

We can demonstrate with the Issue page we are looking at:

1. Drag  the `(!) Issues` tab to Typora. It correctly inserts the following:
   ```
   [Issues 241](https://github.com/typora/typora-issues/issues)
   ```
2. Drag the `typora-issues` breadcrumb to Typora. It correctly inserts the following:
   ```
   [typora-issues](https://github.com/typora/typora-issues)
   ```
3. Click in the Address Bar, and drag the address (the GitHub fav icon) to Typora. **It inserts whatever was in the clipboard.**
4. Repeat step 3, but this time into a Rich Text editor, such as TextEditor (in rich text mode), Byword. The following or its equivalent gets inserted:
   ```
   [regression: URL drag n drop from Safari address bar inserts clipboard, not link · Issue #1612 · typora/typora-issues](https://github.com/typora/typora-issues/issues/1612#issuecomment-404892896)
   ```

**Typora used to behave this way, beginning with the May 1 release** that resolved #899 and #1073. It regressed sometime recently.

**Comment by AlexPasternak** [comment]
Can confirm same bug behavior as @vassudanagunta reports above, should be reopened and fixed.

**Comment by abnerlee** [comment]
I see, dragding the address bar before making it editable do can reproduce the bug

**Comment by vassudanagunta** [comment]
I tried what you allude to... I made it editable, selected the address and dragged... but that just drags the URL, now a link with the expected anchor text.

**Comment by vassudanagunta** [comment]
@abnerlee Any chance this will be fixed? It's been a year since this bug was introduced. I think it is a very common need to add a link to *the currently open webpage*.  

**Typora used to do it correctly!**. It used to do it in **one single step**, consistent with other Mac editors: dragging the page icon from the address bar to the Typora window would produce a link with the page title.

Now it takes **3-4 steps**:

1. Copy & paste or drag the title from the web page content to Typora.
2. (sometimes) Remove the heading formatting as in some contexts Typora inserts copied HTML headings as Markdown headings.
3. Copy the page URL from the address bar.
4. Select the previously copied title text, and press ⌘K.

For people like me who do a lot of linking, these steps are tedious and error-prone.

Please please please make this easier (and consistent with other Mac apps).

**Comment by AlexPasternak** [comment]
Are you sure this doesn't work on latest still? On Safari 12.1 and latest Typora (0.9.9.23.4), I can drag a title OK:

![2019-04-03 13 09 30](https://user-images.githubusercontent.com/1819485/55498514-cf11e500-5611-11e9-8e75-115447470056.gif)

**Comment by vassudanagunta** [comment]
@AlexPasternak Try your test again dragging into TextEdit in *rich text mode*, or into ByWord. That is how it should work. Typora once worked this way.

Right now, Typora is just using the last part of the URL path as the anchor link. It's ignoring all the rich data in the drag and drop.  Typora _does_ do it as expected for cut and pastes, as well as for drag and drops of in-page links (try dragging your name on this page to Typora), though it has some minor issues there as well (try dragging the **`Need more info`** label to Typora).

**Comment by abnerlee** [comment]
should be fixed in new release.  To change default syntax for urls, see #2415

**Comment by vassudanagunta** [comment]
@abnerlee, still doesn't work on `9.9.29.1`. It still just does option 1 from #2415.

Can you confirm that your intent is to make it work just like it does in TextEdit (rich text mode), ByWord and most other rich text editors? 

I just noticed #2464, which you fixed, has regressed too. The title now includes the file extension.

There are so many open bugs and closed bugs that have regressed related to copy &pasting and drag-n-dropping links. There is well established behavior for how those should work on a Mac, and I'm pretty sure in Windows too. Both clipboards support rich data about links. Do you intend to support these conventions that most people expect? 

Please let me know if I should open a whole new bug cataloguing all the issues.

**Comment by abnerlee** [comment]
> I just noticed #2464, which you fixed, has regressed too. The title now includes the file extension.

This is the same behavior like drag & drop a file into Typora

**Comment by vassudanagunta** [comment]
> This is the same behavior like drag & drop a file into Typora

Maybe that should change too?  I'm pretty sure 99% of users would not consider `file extension` to be part of the `title`.

Filename (w/o extension) is a reasonable quick and easy default title to use, but ideally the logic would be, in precedence order:

1. The top heading (the same way you figure out the default filename now). While the filename defaults to this value, sometimes people choose shorter or different filenames. Also, the filename often excludes special characters in the title.
2. The `filename` w/o extension if there is no top heading

**Comment by abnerlee** [comment]
I think use original filename is more safe, to make a title from filename, the original file name should also be capitalized, also, `how-to-write-a-book.md` may better change to `How to write a book`, so it is not just remove the extension. And it does not always follow this case.

A better workaround may be allow uses choose link name candidates, just like we provided some quick actions after user insert images.

**Comment by vassudanagunta** [comment]
> A better workaround may be allow uses choose link name candidates, just like we provided some quick actions after user insert images.

I like that!  A similar dialogue when dragging imags from a browser would be useful to. The image copy settings should have an `Ask` option so the user can decide case by case whether to copy the image to the folder or link to it.

**Comment by abnerlee** [comment]
relates #2415 #2612

**Comment by vassudanagunta** [comment]
Thank you!!!!
