### ISSUE TITLE
"Customized" Font Size ignored when switching themes

### ISSUE THREAD

**Issue by jerclarke** [typora/typora-issues#1657]
Hi, first thanks for this amazing app! Better than the ones I've paid for!

The main issue I'm having is this very-reproducible (at least for me) bug where switching themes always resets the font size from my custom choice in the preferences. 

Typora version: 0.9.9.16.2
macOS: 10.13.6

### Reproduction steps

* Open preferences and set the font size to **Customized**
* Set the font size very very small to make this noticeable (9px)
* Switch to any other theme

### Expected

* New theme loads, customized font applied according to it's relative CSS
* (I understand that it won't always look the same, but it should be what that theme will render for 9px)

### Actual outcome

* New theme loads with it's default font size
* Going back to Preferences and editing the Custom font size fixes it
* Going up+down 1px (back to 9px) makes it show correctly as whatever that theme displays for 9px

---

I like to switch themes and font sizes a lot, basically whenever I switch from daylight to evening light, and depending on whether I'm using Typora as a writing tool (full screen, large text) or a notes tool (thin column next to another app). This bug really gets in the way of being able to quickly "browse" my installed themes to find a good one for this content. Each time I switch, I need to open preferences and up+down the font size for no reason. 

Thanks for trying to find a fix for this. It seems like all you'd need is an extra procedure after theme switching that checks the custom font size and re-asserts the applicable CSS. 

---

Sidenote: Could we get a menu item + keyboard shortcut for **Increase text size** and **Decrease text size**?

That's how all my other editors work, usually with CMD++ and CMD+- like the browsers use. It would be so much more comfortable to use than the Preferences window, and in the case of this bug, I could quickly work around the problem. 

Let me know if you'd like this request for shortcuts in a separate ticket :)

Thanks!

**Comment by jerclarke** [comment]
<img width="698" alt="typora-theme-font-size-demo" src="https://user-images.githubusercontent.com/139995/43812935-9e1ca3a4-9a91-11e8-92bd-61ef23766003.png">

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by jerclarke** [comment]
Nice, thank you! 

I guess I can test it when the new version comes out? Still seeing 0.9.9.17.4 as the version on the site.

**Comment by jerclarke** [comment]
Oh it does work, sorry! I didn't even try that. The changelog made me think this wasn't in the most recent update but I guess you added the fix and it updated itself!

Thanks!

Please still consider adding CMD++ and CMD+- for shrinking/growing the text size without entering the settings :)
