### ISSUE TITLE
Export to PDF: Unnecessary Space at document beginning

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#1866]
When exporting to PDF, it leaves an unnecessary space on the first page.

Fist Page:
![image](https://user-images.githubusercontent.com/22482891/46895273-8892b900-ce2c-11e8-8562-b20833ecacce.png)

Second Page:
![image](https://user-images.githubusercontent.com/22482891/46895300-a4965a80-ce2c-11e8-9285-016a1dfa3b01.png)

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by aztekyi** [comment]
Hello, I still have this issue on Windows and I am on the latest version. I've tried exporting with different themes and the first page still has that unnecessary space.
