### ISSUE TITLE
Inline Math Blocks Not Rendering Upon Re-open in New Window

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#2176]
Issue: I have a table where I'm using a lot of inline MathJax. However upon closing and re-opening the document in a new window, almost all of the MathJax is in purple text and doesn't render until I edit it (I'm having to delete a character (in my case a `)` and inserting it back).
<img width="108" alt="screen shot 2019-02-12 at 9 24 41 pm" src="https://user-images.githubusercontent.com/12269792/52684798-167ecd80-2f0d-11e9-9e4d-85f3cf916cd7.png">
None of the MathJax gets re-rendered even if I place my cursor upon it; I even switched to Source Code Mode and all the MathJax is there, just not getting rendered. I have to edit it for it to render again.
Platform: macOS 10.14.2
Typora version: Latest (Version 0.9.9.21.1)

Steps to reproduce: 

- Insert several lines of inline MathJax (does not need to be in table as this happens every time I place inline MathJax somewhere)
- Close Typora document
- Re-open Typora document in new window from already open Typora app

Hope this helps.

**Comment by abnerlee** [comment]
Possible to provide the sample *.md file?

**Comment by justnealpatel** [comment]
Definitely. I've attached it. What you can do to replicate this is just open the general folder in Typora and just right-click this file and choose Open in New Window. Similarly, the steps to reproduce should also generate this error.
[Data Structures.md.zip](https://github.com/typora/typora-issues/files/2861354/Data.Structures.md.zip)

**Comment by abnerlee** [comment]
fixed in new release

**Comment by justnealpatel** [comment]
@abnerlee This bug reappears in the current version 0.9.9.23.4 (2293).

**Comment by justnealpatel** [comment]
@abnerlee this error is still occurring in version 0.9.9.23.4 (2293).

**Comment by abnerlee** [comment]
#2399
