### ISSUE TITLE
Did autopair stop working in the last version? 

### ISSUE THREAD

**Issue by luispuerto** [typora/typora-issues#2214]
Hey I think the autopair feature has stopped working in the last version. Am I right? 

![2019-02-21 09 39 13](https://user-images.githubusercontent.com/22882880/53151796-ae8b4f80-35bc-11e9-8725-5cc39545bdcf.gif)
![screen shot 2019-02-21 at 09 39 37](https://user-images.githubusercontent.com/22882880/53151835-bd720200-35bc-11e9-97d3-51a470ee199a.png)

**Comment by justnealpatel** [comment]
Stopped working for me also after updating.

**Comment by hydnwang** [comment]
Same here, all the brackets and parentheses stopped working after updating.

**Comment by NachiGithub** [comment]
For the time being, if you want to roll back to the previous version, it's here: https://typora.io/download/Typora-0.9.9.21.1.dmg

**Comment by abnerlee** [comment]
fixed in new release

**Comment by justnealpatel** [comment]
Quotes are still not being matched on version 0.9.9.23.4 (2293).

**Comment by luispuerto** [comment]
@justnealpatel not in my case. They are working properly here.

**Comment by justnealpatel** [comment]
@luispuerto it somehow works now. When I was using it a few days ago, it wasn't working.

**Comment by abnerlee** [comment]
> EDIT: It's not auto-matching inside a code block

which punctuation ?

**Comment by justnealpatel** [comment]
@abnerlee quotations (both single and double).

**Comment by luispuerto** [comment]
I confirm the issue is happening here too.

**Comment by abnerlee** [comment]
should be fixed

**Comment by luispuerto** [comment]
I can confirm that is fixed 😛

**Comment by feuyeux** [comment]
It cannot work for me,yet.
Version 0.9.9.33.2 (4442)
mac os version 10.15.4

**Comment by luispuerto** [comment]
0.9.9.33.2 (4442) is working for me on 10.15.5

Anyhow, If it's a new issue open a new issue 😉
