### ISSUE TITLE
Brazilian Portuguese dictionaries are downloaded with wrong name format

### ISSUE THREAD

**Issue by jjnilton** [typora/typora-issues#2487]
When downloading the Brazilian Portuguese dictionary it saves the file as pt-BR.aff and pt-BR.dict instead of pt_BR.aff and pt_BR.dict.

**Comment by abnerlee** [comment]
should be fixed in latest version

**Comment by luisfelipesdn12** [comment]
@abnerlee, I'm still having issues with that :/
The `pt-BT` language support installation just doesn't works
