### ISSUE TITLE
Hyper Link Auto Jump Not Working After Recent Update

### ISSUE THREAD

**Issue by Wangwj98** [typora/typora-issues#2622]
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.49-1-MANJARO
Typora: 0.9.72-1

After the recent update of Typora, when I press `Ctrl` and left click my mouse on any hyper link, it will not auto jump to the specific website in the browser.

How can I fix it?

**Comment by farzadmf** [comment]
I'm facing the exact same issue on Manjaro, and my kernel is `5.1.15-1-MANJARO`

**Comment by Wangwj98** [comment]
I hope this bug can be fixed some day when I was still alive. LOL

**Comment by farzadmf** [comment]
I'm pretty sure everything would work better (and issues fixed faster) if Typora was open source, but too bad the creators decided to go the "closed-source" way :(

**Comment by abnerlee** [comment]
Cannot confirm on Ubuntu.

Are you using Chrome or Firefox as default browser? 
and does `xdg-open https://google.com` work?
and click `help` -> `More Topic...` from menu bar open web page?

**Comment by farzadmf** [comment]
Thank you @abnerlee for answering. It's happening for me on Manjaro (which is arch-based), but as I said in my first comment, it was working fine, but at some point (most probably because of an update), it stopped working

**Comment by abnerlee** [comment]
@farzadmf Thanks for the info, would you try send us <hi@typora.io> the log file? (refer http://support.typora.io/Report-Bugs/#logs)

**Comment by farzadmf** [comment]
@abnerlee I sent the email, and I put some comments in the email that I'm repeating here:

> I cleaned up the log and then I did this: open Typora, open a document with a hyperlink, try to open with `ctrl+Click`. There's an error regarding `Buffer` in the log file, but I think that's when Typora starts, and I'm not sure if that's the reason that this is happening. And when I `ctrl+Click` on the hyperlink, I don't see any additional message in the log.
As a side note, I even tried opening dev tools to see if I see an error there, but it seems that the action of clicking is basically being ignored, but I don't see anything happening in the dev tools either.

Hoping to get this issue fixed

**Comment by farzadmf** [comment]
Hi @abnerlee , any updates on this? This is one of my most-used features that I'm missing

**Comment by farzadmf** [comment]
Hi @abnerlee , just a thing I noticed that I thought could be useful in resolving this: if I select some text in the editor, and then select `Search with Google`, it works (it opens a browser).

But if I right-click on a link and select `Open Link`, it doesn't work (I think this has the same behavior as `Ctrl+Click`)

**Comment by jonrandy** [comment]
Happens for me too - both on Ubuntu and macOS

**Comment by farzadmf** [comment]
For me, the issue was fixed. For some reason, I had to re-install my Manjaro Linux, and when I did that, the hyperlinks started working again

**Comment by jonrandy** [comment]
Still present for me in latest version - both on Ubuntu and macOS - so it seems it isn't OS specific

**Comment by jonrandy** [comment]
I should point that my issue is for links *within* the document

**Comment by abnerlee** [comment]
Should be fixed. 

Can this still be reproduced on latest version?

**Comment by jonrandy** [comment]
Just updated on Mac - still broken. Update on Linux downloading...

**Comment by jonrandy** [comment]
Still broken on Linux too. Shall I send you the file I'm working with?

**Comment by abnerlee** [comment]
Fixed in 0.9.85

**Comment by jonrandy** [comment]
Seems like almost fixed, but still not working correctly - I've added some links in the same document to jump back to the top. Weirdly, they don't work. They are OK on other Markdown viewers

**Comment by abnerlee** [comment]
What kind of links are you using?

**Comment by jonrandy** [comment]
They're the same as the ones that weirdly are already working.


The targets are in this form `<a id="I">I</a>`


And the links are in the form `[I](I)`

The new ones I added are in the same form, but all (attempt) to link to the header which is marked with the id `top`

The original ones work, but the new ones don't - which is odd as I'm doing everything the same way.

Viewing the doc on another editor (iA writer) has all links working as expected

**Comment by abnerlee** [comment]
You should use 
```
<a name-"I">I</a>

[I](#I)
```

for anchor links.

see http://support.typora.io/Links/#internal-links

**Comment by jonrandy** [comment]
Okay, I'll try that. Why though, are all the links except the 'top' links working when they're all using exactly the same linking technique? Something seems amiss

**Comment by jonrandy** [comment]
The document in question can still be found at the link above if you want to look at it

**Comment by abnerlee** [comment]
The previous  'top' links works because Typora supports links to headings even without the "<a id='xx'>" tag. You can refer to the first example in http://support.typora.io/Links/#internal-links, or try in Github

### header 3

text
text

[Link to header 3](#header-3)

**Comment by jonrandy** [comment]
Changing all `id` attributes to `name` attributes did the trick :+1:
