### ISSUE TITLE
Inconsistent behavior of Home/End

### ISSUE THREAD

**Issue by asherber** [typora/typora-issues#2693]
Using 0.9.73 on Windows.

Within a paragraph of text, `Home` moves to the beginning of the paragraph, and `End` moves to the end of the paragraph. Standard Windows behavior would be to move to the beginning/end of the current line.

Within a fenced code block, `Home` does indeed move to the beginning of the current line, but `End` moves to the control at the end of the block where the language is specified.

**Comment by farzadmf** [comment]
I can confirm that this is also happening on Manjaro Linux within a code fence, and honestly, this is **really annoying**.

Moreover, if you try to do `Shift+Home` to select a line in the code fence, it doesn't let you, and your selection is cleared every time.

Other changes causing inconsistent behavior compared to before that I noticed:
- Before: I right-click on a directory and add a file; I would then could rename the file.
  Now: when I add a new file, it's added as `untitled.md`, and I need to do a second right-click to rename the file

- Before: when I hovered over the file tree, my mouse cursor would change to "hand"
  Now: the mouse cursor doesn't change when hovering over the file tree

**Comment by durianking** [comment]
I am having the same issue with selection as reported by @farzadmf .

Other than `Shift+Home`, text selection using `Shift+End` from beginning of line also no longer working after the recent upgrade.

Using Typora windows version 0.9.73(beta).

**Comment by lbnv** [comment]
I can confirm it too. Typora ver. 0.9.73

**Comment by christophcemper** [comment]
YEP; confirmed and super annoying. 

In addition to that the home/end characters fail to work as they used to when renaming files.

**Comment by christophcemper** [comment]
To clarify

It now WORKS when copy/pasting within the same file/folder

It is still DEFECT when copy/pasting between different file/folders

**Comment by ashawkey** [comment]
Having the same problem too (Windows version 0.9.73).

**Comment by ashawkey** [comment]
In addition, `home` and `end` in math block will make it unable to input any character further.

**Comment by MostlyArmless** [comment]
Confirmed on 0.9.73 as well, hope this gets prioritized.

**Comment by christophcemper** [comment]
High prio on this please @abnerlee - it breaks the core of working with Typora.

Similar issues with home/end when "renaming a file in the explorer"

Actually downgrading now to 0.9.71 as it's unbearable to work with.

**Comment by abnerlee** [comment]
fixed

**Comment by fresheneesz** [comment]
This is still not fixed for Source Code Mode. Created #3173 for it
