### ISSUE TITLE
Honor the OS's cursor blink settings 

### ISSUE THREAD

**Issue by nikpmr** [typora/typora-issues#2856]
Typora cursor blinks regardless of whether the user has set the caret to blink faster or slower than normal. This would be an excellent bug to fix with Typora being a text editor.

See [this electron issue](https://github.com/electron/electron/issues/10668) for a description of the bug. It seems to have been fixed in Electron 5+.

**Comment by abnerlee** [comment]
https://github.com/electron/electron/issues/10668

**Comment by nikpmr** [comment]
The issue is fixed if one tries running Typora using a newer version of electron.exe.

**Comment by abnerlee** [comment]
should be fixed

**Comment by dmitriydligach** [comment]
This is still a problem for me, unfortunately. Please fix this!
