### ISSUE TITLE
Mermaid diagrams not exported in Word

### ISSUE THREAD

**Issue by LucaBlackDragon** [typora/typora-issues#2878]
**Environment:**

Typora 0.9.77(beta) on Windows 10

**Issue:**

Mermaid diagrams are not showing if a Markdown document is exported to Word.

**Test document:**

```
# Test document

This is a test document.

If exported in Word (.docx), the following mermaid diagram won't show in the document:

` ` `mermaid
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
` ` `

(sequence diagram taken from the [Mermaid official documentation](https://mermaidjs.github.io/#/sequenceDiagram))
```

> NB: here I have added spaces between the backticks in the mermaid code block, otherwise they would have "triggered" Github's own markdown parser.
> [This archive](https://github.com/typora/typora-issues/files/3681091/Test.document.zip) contains an unmodified copy of the test document (i.e. without additional spaces)

**Exported document:**

![immagine](https://user-images.githubusercontent.com/3714010/66044212-58eb2e00-e521-11e9-808e-49b00ec54a0b.png)

**Related issues:** 

#1182

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by LeShrimp** [comment]
Unfortunately still experiencing this on Linux with Typora 0.10.10.

```markdown
# Mermaid export test

```mermaid
graph LR
A-->B-->C
` ` `
```
Note: The space between the ending backticks is not in the original file.

I get this message but it never stops:

![Screenshot_2021-05-25_09-43-23](https://user-images.githubusercontent.com/12305148/119459183-c0c93a80-bd3d-11eb-97d1-92069cd3008a.png)

**Comment by abnerlee** [comment]
Any log in console (View -> Toggle DevTools)?

**Comment by LeShrimp** [comment]
All I get ist an XHR request:
```
XHR finished loading: POST "https://pinpoint.us-west-2.amazonaws.com/v1/apps/4eed..…/events".
```
But I guess this is not related.

**Comment by abnerlee** [comment]
it is not related.

What's your pandoc version, and can it be exported to RTF or other formats?

**Comment by LeShrimp** [comment]
```
$ pandoc --version
pandoc 2.14
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4, ipynb 0.1.0.1
```
I can export to RTF, but the diagram is only exported as plain text. When I export to PDF or HTML the diagram is perfectly rendered, no problem. 

Exporting to ePub also freezes Typora.

Hope that helps.

**Comment by JohnMarkHowell** [comment]
Has anyone come up with a solution to this problem?

**Comment by abnerlee** [comment]
It is fixed already for "Export to word"

> I can export to RTF

RTF does not support images or sharps.
