### ISSUE TITLE
[BUG] Unable to export HTML after upgrading to macOS 10.15

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#2895]
It may be a security policy issue for the new system. After clicking "Export HTML", there is no response and the HTML file cannot be exported.

**Comment by abnerlee** [comment]
Please try shutdown and then restart macOS. I got it fixed in this way.

**Comment by MadMaxChow** [comment]
Restarted macOS, no, delete and reinstall Typora

**Comment by abnerlee** [comment]
@MadMaxChow did you give Typora read & write privilege on full disk? When you create new file and click save, will save dialog popup?

**Comment by yorkew-east8** [comment]
I have tried everything (Restarted macOS, delete and reinstall Typora , and give Typora read & write privilege on full disk), still the same problem...

**Comment by abnerlee** [comment]
> When you create new file and click save, will save dialog popup?

**Comment by yorkew-east8** [comment]
> @yorkew-east8 When you create new file and click save, will save dialog popup? And you are also on macOS 10.15, right?
New file and click save looks fine, file saved and no dialog popup.
And yes this problem happens  after I upgraded to macOS 10.15.

**Comment by abnerlee** [comment]
I released a new version 0.9.9.29.1 which should fix this (in my test).

Please try upgrade typora, then restart macOS

**Comment by yorkew-east8** [comment]
> I released a new version 0.9.9.29.1 which should fix this (in my test). @yorkew-east8
> 
> Please try upgrade typora, then restart macOS.

Thanks for quick response, 
I upgraded to 0.9.9.29.1 and restart macOS, but it didn't works. delete and reinstall typora, then restart macOS, still got the problem.

Tried more actions, maybe helpful:
1. In File Tree view , click "+" , create file OK, edit and save is also OK.
2. Menu -> File -> New , then save, no dialog popup and file not saved.

**Comment by yorkew-east8** [comment]
> 2. Menu -> File -> New , then save, no dialog popup and file not saved.
in this case, Typora can't be closed, and select file in the Tree View is no response

**Comment by abnerlee** [comment]
Have you try delete all Typora related files using tools like AppCleaner?

**Comment by abnerlee** [comment]
Any try this in terminal? (from https://twitter.com/LeoNatan/status/1169738294244139009) @yorkew-east8 
```
defaults write abnerworks.Typora NSUseRemoteSavePanel -boolean NO
```

**Comment by yorkew-east8** [comment]
@abnerlee 

I got it fixed by delete Typora with AppCleaner and reinstall, so it's old configs?
Now everything works fine again, Thank you!

**Comment by chaos1952** [comment]
@yorkew-east8 Thank you, Typora Version: 0.9.9.32.1 (4191), Same problem on MacOS 10.15, but can not fix by the same way as you did,  It still Crashed by "Export to .docx ", I've installed pandoc 2.9.2.1 from Github, and It still …… OMG
