### ISSUE TITLE
Ctrl+Shift+arrows at beginning/end of paragraph

### ISSUE THREAD

**Issue by svoulaz** [typora/typora-issues#2964]
The key combination Ctrl+Shift+arrows works fine to select by word, but if the selection starts at the end or at the beginning of a paragraph, then any "direction change" will move the caret to the next or previous paragraph respectively, loosing last selection.

As an example, using the text of this same report, imagine the following:
1) position the cursor at the end of the above paragraph after the full stop ('.')
2) press and hold Ctrl+Shift
3) press Left Arrow three times to select "loosing last selection."
4) press Right Arrow (while still holding Ctrl+Shift), aiming to select "last selection."
The cursor moves at the beginning of the next paragraph, just before "As an example" and the previous selection is lost.

Running on Windows 10

Great job!

**Comment by abnerlee** [comment]
should be fixed.

relates #1164

**Comment by svoulaz** [comment]
Not fixed.
Now at step 4 the cursor moves at the end of the paragraph and the selection made so far is lost.
Also, if the operation is performed at the very end of the text, it's no longer possible to use the right arrow key to move right (thus modifying the selection) while holding Ctrl+Shift. 

Another strange behavior, related to cursor handling at the end of a paragraph:

1) Type some text in a blank document, followed by [return] - the cursor is now at the beginning of the following line
2) Hold Ctrl+Shift and press LEFT arrow key

The cursor is lost and it will not come back unless by clicking with the mouse. Happened at least twice, not always reproducible - can't find the triggering sequence. Seems to happen more often when pasting.

**Comment by abnerlee** [comment]
The selection is not lost, it is not rendered, since actually no visible text, but "\n" is selected.

The future improvement will be done in #1164, so I will close this one.
