### ISSUE TITLE
PDF export does not support <img /> tags

### ISSUE THREAD

**Issue by jrogelth** [typora/typora-issues#3046]
When using `<img />` tags to have more control over the size of the images exported, the resulting PDF does not embed the image. If the syntax is changed to normal markdown (i.e. `![]()`) the image is exported, but the size if not manageable.

**Comment by abnerlee** [comment]
should be working in new release

**Comment by fabern** [comment]
This issue still appears using the most recent version "0.9.9.31.4 (4005)" on macOS.
Was the fix in a more recent version?

**Comment by abnerlee** [comment]
same with #3120?

@fabern what's your img tag look like, or possible to provide a sample file?

**Comment by TheKashe** [comment]
I have the same problem, unfortunately it's not reproducible in a test document.

In my document, which I can't share, two images, both resized and using img tag, are not exported or printed.

If I try to do the same with a new document, it works.

**Comment by abnerlee** [comment]
So it's same with #3120

**Comment by jvsteiner** [comment]
I also have this problem in v 1.0.2 (yes, I paid for a license the day it went v1)  Thanks for a great product
