### ISSUE TITLE
PDF export breaks links

### ISSUE THREAD

**Issue by senlin** [typora/typora-issues#3176]
I have no idea when this happened as it was never a problem before.

Running latest version (Version 0.9.9.31.4 (4005)) and when doing a PDF export now, any links in the document are no longer clickable. The still look like a link though (blue and underlined).

A workaround is to Print the document instead and then Save as PDF.

**Comment by tangramor** [comment]
I met the same problem...

**Comment by abnerlee** [comment]
should be fixed in lastest version

**Comment by senlin** [comment]
Yes, it works again, but the pound key (#) is replaced with `%23` so links containing one still don't work as they often lead to a 404.
