### ISSUE TITLE
Cursor moves into YAML front matter when typing with MS Pinyin

### ISSUE THREAD

**Issue by lynzrand** [typora/typora-issues#3318]
Observed in v0.9.85 (beta). Windows version: Build 19569.

# Steps to reproduce:

1. Use MS Pinyin or Microsoft Japanese IME as input method.

2. Create a Typora document with YAML front matter.

3. Type one letter in document body. The cursor behaves normal.

  ![图片](https://user-images.githubusercontent.com/10259119/75599681-2b131100-5ae2-11ea-86cb-9d8cf9b0d2a6.png)

4. Type another letter, the cursor suddenly moves into front matter.

  ![图片](https://user-images.githubusercontent.com/10259119/75599697-4b42d000-5ae2-11ea-9b36-e35747036cd0.png)

# Notes

This problem does not always occur. From my experience, it only happens after the YAML front matter is created _and_ one has not focused any other window after that (e.g.  switch to a web browser and switch back).

This issue wasn't observed in v0.9.83.

**Comment by 01010101lzy** [comment]
Here's a gif showing the issue.

![typora](https://user-images.githubusercontent.com/10259119/75599820-8f82a000-5ae3-11ea-958a-e22ed07555d6.gif)

**Comment by abnerlee** [comment]
should be fixed

**Comment by varm** [comment]
> should be fixed

But it remains.
Typora version: 0.10.7
Windows: Windows 10 20H2

![error](https://user-images.githubusercontent.com/1610280/117530313-0502ce00-b00f-11eb-9a13-da52b1fa3f3e.gif)

**Comment by abnerlee** [comment]
fixed in 1.3.6

**Comment by FrankSFLYS** [comment]
> fixed in 1.3.6

The problem still exists if YAML front matter is more than two lines or opening a file. Version 1.2.5

I'm using a theme that requires front matter to work, and every time I edit the title the cursor jumps. So I hope this to be completely solved.

**Comment by FrankSFLYS** [comment]
I have tried versions 1.3.8 and 1.3.3-dev, it still exists.

**Comment by FrankSFLYS** [comment]
I have switched to Version 1.3.6 and it still remains. 😭I'm using Windows 11 and MS Pinyin.

**Comment by hundan2020** [comment]
问题依旧存在 当前版本为1.5.9

**Comment by yuanzhouxue** [comment]
Problem remains on version 1.6.7 on Windows 11

**Comment by NipGeihou** [comment]
Problem remains on version 1.8.10 on Windows 11

**Comment by walterke1001** [comment]
原来这是个远古问题了，蚌埠住了，现在都1.8.1啦，问题还是存在！

**Comment by fqmoon** [comment]
没想到吧，1.9.5 了还没修复 [doge]

**Comment by plumoat** [comment]
1.12.2 依然存在 只能在源码编辑模式下输入中文 什么时候能修好啊
Problem remains on version 1.12.2. when will it be fixed?
