### ISSUE TITLE
Text Disappears and Scroll Jumps (Syncing Issues) While Editing When File is on iCloud Drive (0.9.9.35.2)

### ISSUE THREAD

**Issue by quixado** [typora/typora-issues#3884]
## Issue
Recent text disappears while typing.

## Steps to Reproduce 
- Open .md file which is in a folder on iCloud Drive. Large or small, but should have enough content for scrolling.
- Type for a indeterminate length of time (eg: note taking in a meeting)
- Manually saving (CMD+S) in-between seems not to impact frequency or occurrence.
- Able to repeatedly reproduce on this configuration.

## Observation
- Recently typed text will occasionally disappear and cursor will jump to some other location in the file.
- If immediately caught when it happens and pausing, some or all recent text will repopulate within 15-20 seconds.
  - If not and typing continues, some to all text is lost. Subsequent text is in different place in file

## System
- MacOS 10.15.7
- Typora 0.9.9.35.2
- General
  - "Save and Recover" - Checked and Greyed out.

## Hypothesis
- A conflict with iCloud sync and Typora auto-save syncing. Not experiencing in other apps under same iCloud Drive file structure.

**Comment by abnerlee** [comment]
Possible to send us <hi@typora.io> since we cannot reproduce this?

**Comment by quixado** [comment]
> Possible to send us [hi@typora.io](mailto:hi@typora.io) since we cannot reproduce this?

@abnerlee Just sent an email with a screen video capture and with additional information to help in investigating. Happy to help troubleshoot.

Cheers!

**Comment by callimero** [comment]
I have the same Problem on Window 10 saving on a network drive from my employer over VPN. 
Suddenly all text or parts disappear. There are other editors which have some "safe save" (?) which writes the auto-save to the drive in one piece and then renames it (I think thats a way to do it). 

This behavior always scares the sh*** out of me and I don't want to care about such things while working.

**Comment by ryanmholmes** [comment]
*Bump*. I have this precise issue as well with a .md saved in iCloud. Windows 10, most recent non-Insider build (19041.1052) afaik. But it's happened for the last several versions also. I've concurrently noticed that multiple numbered versions of files are appearing in iCloud that seem unrelated to opening them on another device. They will have names like xyz(1).md, xyz(2).md, etc., with a non-numbered file name as the most recent one. As a temporary workaround, I've turned off Typora's autosave since I need to use iCloud for syncing with 1Writer on iOS.

**Comment by abnerlee** [comment]
Does this happen for laste icloud drive and typora 0.10.11?

I tested iCloud drive on my PC, and it seems working fine. 

---
duplicated with #3107

**Comment by ryanmholmes** [comment]
Yes, it’s happening right now to me as a test. I’m on that version of Typora and iCloud 12.4.103.0. I believe that’s the most recent version of the latter but am not sure.

This time, with auto save on, I’ve been hitting ctrl+v to paste, and the cursor will sometimes jump at that moment to another seemingly random line and not execute the paste. Don’t know if the pasting is part of it or just a coincidence. When I check my iCloud folder a second copy has been created in the background with the suffix (1). That new copy has the syncing icon, while the original has a fully synced status and a modified time that seems current while the copy has one from 20 minutes ago.

I’ll work on a screen recording though it may not show much.

Thanks,

Ryan
________________________________

**Comment by abnerlee** [comment]
I can reproduce now on Windows + iCloud / OneDrive with a slow network, we will fix it in next version up.

On macOS version, I believe it is already fixed in 0.10.x

**Comment by quixado** [comment]
Can confirm the issue still persists on MacOS 0.10.11 (5372). Files saved on an iCloud Drive will periodically lose blocks of text and sometimes cursor position. Text can usually be recovered by selecting undo `cmd+z` 1-3 times, but if not noticed, text will be lost.

Occasionally, the following prompt will interrupt work:

> **The document '{{file name.md}}" could not be saved. The file has been changed by another application.**
> Click Save Anyway to keep your changes and save the changes made by the other applications a version, or click Revert to keep the changes from the other application and save your changes as a version. You can also click Save As to save your changes to a different file.
> Buttons: Save Anyway | Revert | Save As…

This sometimes appears with no recent changes to the file or sometimes when in a state of lost text. No other applications are open and using the file when this occurs.

OS: Mac OS 11.4

HtH.
