### ISSUE TITLE
When I use Chinese in Mermaid, the content in the graph is not displayed completely。

### ISSUE THREAD

**Issue by gaofengg** [typora/typora-issues#4033]
When I use Chinese in Mermaid, the content in the graph is not displayed completely。
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15

**Typora**
Version 0.9.9.35.2 (4715)

**Comment by abnerlee** [comment]
should be fixed

**Comment by zooyf** [comment]
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/d49ba370-f34d-42d5-80ef-3fd8e8791977" />

Not fixed in Version 1.10.10 (7411) on macos 14.2.1 (23C71)

```mermaid
graph TB
    subgraph "A2A Teams系统"
        A[Host Agent] --> B[MCPHub Client]
        C[General Agent 1] --> B
        D[General Agent 2] --> B
    end
    
    subgraph "MCPHub Hub"
        B --> E["MCPHub Server
        localhost:3000"]
        E --> F["Smart Routing
        /mcp/$smart"]
        E --> G["Group Endpoints
        /mcp/[group]"]
        E --> H["Server Endpoints
        /mcp/[server]"]
    end
    
    subgraph "MCP Servers (各种协议)"
        I["Pandas Server
        stdio"]
        J["Playwright Server
        stdio"]
        K["Remote API Server
        sse"]
        L["Web Server
        streamable-http"]
    end
    
    subgraph "MCPHub Protocol Conversion"
        E --> M[Protocol Adapter]
        M --> N[Stdio Manager]
        M --> O[SSE Manager] 
        M --> P[HTTP Manager]
    end
    
    N --> I
    O --> K
    P --> L
    M --> J
    
    subgraph "Configuration"
        Q[mcp_servers.json] --> E
        R["MCPHub Dashboard
        Real-time Monitoring"] --> E
    end
    
    classDef a2aSystem fill:#e1f5fe
    classDef mcpHub fill:#f3e5f5
    classDef mcpServers fill:#e8f5e8
    classDef config fill:#fff3e0
    
    class A,B,C,D a2aSystem
    class E,F,G,H,M,N,O,P mcpHub
    class I,J,K,L mcpServers
    class Q,R config
```
