### ISSUE TITLE
old files with inline math do not render at all

### ISSUE THREAD

**Issue by aerioeus** [typora/typora-issues#4040]
I have a couple of .md files which have some math in it.
When I open them with the newest version (0.9.97) the equations are not being rendered.

Merci in advance

G

![image](https://user-images.githubusercontent.com/23232503/101928684-313c2f00-3bd6-11eb-9625-b03cdc84b34d.png)

**Comment by CocytusDuo** [comment]
Same problem

**Comment by robb-brown** [comment]
Same problem. This includes the help documents.

Also, any typed math blocks do not render (and the preview while typing just says "empty math block"). However, pasting (as plain text) an entire block typed in another editor, including opening and closing $$, seems to work. However, if the resulting block is clicked on, opening the editor, when the editor is closed the block disappears.

**Comment by Theigrams** [comment]
Same problem. All of the inline math blocks do not render in the newest version.

**Comment by abnerlee** [comment]
We just updated a fix, it should be working now after you check updates again..

**Comment by Kanishk56** [comment]
Is anyone still facing the problem of inline math not working , it is not working for old documents? I have the latest version, all updates are there

**Comment by robb-brown** [comment]
Nope, the Dec. 13 update fixed the problem for me, old and new documents.

**Comment by aerioeus** [comment]
I can confirm that. It's all working now.
