### ISSUE TITLE
Search on large documents is unresponsive when typing in the search bar

### ISSUE THREAD

**Issue by tmairegasnighto** [typora/typora-issues#4278]
Because the Search is searching the entire document with any keypress of the Search bar, the app becomes unresponsive when searching large documents.

My large document (of 27K words) makes the search difficult to use as-is.   

Workaround: Type the search string elsewhere and then paste it into the search window.

Similarly, hitting the case-sensitive and whole-word buttons in the Search bar make the app briefly unresponsive.

I would also recommend a "not found" message when the up/down arrows in the search bar are used and there are no results.

In a similar vain, large documents need a right-hand scroll bar.

**Comment by abnerlee** [comment]
What's your version and possible to provide a sample md file that is slow on search?

**Comment by tmairegasnighto** [comment]
Version 0.9.98.  Too much private info to provide sample.  Document has an average amount of markup - it's a journal.  Has 27K words spanning 2 years of note taking.

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by zwcn** [comment]
Hi, I had the same issue for quite a long time and I'm still experiencing slowness in the latest version v0.10.4 on Mac. My file is 847KB. Do you mind me sharing the file so that you can analyze why it's slow?

**Comment by abnerlee** [comment]
Sure, thanks, please send to <hi@typora.io>.

and it is slow to load or slow to search?
