### ISSUE TITLE
Automatic updater does not honor the previous installation location

### ISSUE THREAD

**Issue by nedsociety** [typora/typora-issues#4334]
The automatic updater forces you to install it in the default location (C:\Program Files\Typora) instead of the location where the previous installation is in. As result you have two separate installation after the update, instead of previous version being overwritten by the new one.

**Comment by abnerlee** [comment]
64 or 32 bit?

And no typora pre-version installed in C:\Program Files\Typora?

**Comment by nedsociety** [comment]
64bit. In my case the previous version was on D:\Programs\x64\Typora.

**Comment by abnerlee** [comment]
should be fixed

But may work from upgrading from v0.11

**Comment by nedsociety** [comment]
Still not working.

1. Installed older Typora on prev location: `typora-update-x64-1213.exe /DIR=D:\Programs\x64\Typora`
2. Updated to v0.11 via auto-updater.
3. Both `D:\Programs\x64\Typora` and `C:\Program Files\Typora` exists.

Expected behavior is to overwrite v0.11 into `D:\Programs\x64\Typora`.

**Comment by nedsociety** [comment]
I also noticed that the installer for the previous version (v0.9.98) has its file content altered. And the installer GUI does not contain the step for directory specification. IIRC it had one. This is strange.

Is it just me or did you change the prev version installers to force the installation location?

**Comment by abnerlee** [comment]
should work from 0.11.0 to 0.11.1, etc..

**Comment by nedsociety** [comment]
> should work from 0.11.0 to 0.11.1, etc..

Oh, I misunderstood it 🤦 So then there's no way to check it working for now.

**Comment by abnerlee** [comment]
There are issues on 0.11.0, 0.11.1, so may be from 0.11.2 to 0.11.3...

**Comment by nedsociety** [comment]
Tried updating 0.11.2 -> 0.11.7 today, it still doesn't honor the previous location. The issue should be reopened.

**Comment by davan690** [comment]
I have been deleting original installation and reinstall the update. This still hasn't changed for the latest version for me too

**Comment by abnerlee** [comment]
`typora-update-` are for updates after installed by `typora-installer-`

Firstly, `typora-installer-` needs to be installed and user will select a install location and it will be recorded. Or it will use previously installed location of `typora-installer-`.

So, did you try uninstall Typora before step 1?

**Comment by nedsociety** [comment]
My first installation was done via chocolatey [which seems to use `update-`](https://github.com/FranklinYu/chocolatey-packages/blob/master/automatic/typora/tools/chocolateyInstall.ps1#L6) so it's pretty likely that I've never run `typora-installer-*` before. To make sure of it, which registry key has the the last location recorded?
