### ISSUE TITLE
Underscores in inline LaTeX after square bracket interpreted as italics in source code mode

### ISSUE THREAD

**Issue by rogino** [typora/typora-issues#4481]
- [ x] Searched existing issues to avoid creating duplicates.

- [ x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ x] Searched http://support.typora.io/

----

**Describe the bug**
In an inline LaTeX block, underscores can be interpreted as a Markdown italics command: `$[a]_b$`

```
$[a]_b$ Italicized text $\left[a\right]_b$ Non-italicized text
```

**To Reproduce**
1. Enable inline LaTeX
2. Go to source code mode
3. Type `$[a]_b$ Italicized text $\left[a\right]_b$ Non-italicized text`

**Expected behavior**
The underscore is not interpreted as a Markdown command when in an inline LaTeX block.

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/19989743/122666280-78981d80-d200-11eb-98f5-36fa569499f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64, Build19042

**Typora Version**
0.10.11

**Comment by abnerlee** [comment]
should be fixed

**Comment by AngusMcLure** [comment]
I am still having this problem exactly as described here

Operating system: Mac OS Mojave
Typora version: 1.3.7

**Comment by abnerlee** [comment]
@AngusMcLure Could you provide a markdown sample code ?

**Comment by AngusMcLure** [comment]
Here is some markdown sample code with the funky behaviour:

'''
Blah blah $t_{tot}$ or $N_{tot}$
'''
Note that the issue only occurs in the source mode
