### ISSUE TITLE
Context menu is not a modal

### ISSUE THREAD

**Issue by Geeyun-JY3** [typora/typora-issues#4546]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Context menu is not a modal

**To Reproduce**
Right click on writting area

**Expected behavior**
Context menu is a modal

**Screenshots / Screencasts**
Something strange like
![image](https://user-images.githubusercontent.com/49396421/126864805-5d09bcc2-6ba7-44f2-afd3-c948b806dd53.png)
![image](https://user-images.githubusercontent.com/49396421/126864799-1c9b4dfc-59cb-4615-baf5-adf4c49de38a.png)

**Sample Markdown File**
no need

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1110 64bit

**Typora Version**
0.11.2(beta)

**Additional context**

**Comment by abnerlee** [comment]
should be fixed in 0.11.5

**Comment by Geeyun-JY3** [comment]
I can still reproduce this
![image](https://user-images.githubusercontent.com/49396421/126864805-5d09bcc2-6ba7-44f2-afd3-c948b806dd53.png)
by right click on writting area first, then open the main menu.
 Does it work as intended?

**Comment by Geeyun-JY3** [comment]
Now the context menu would be closed after opening the Preferences.

Tested in Typora 1.5.2-dev, Windows 10 21H1 19044.2486.
