### ISSUE TITLE
cursor floats when typing inline formula on MacOS

### ISSUE THREAD

**Issue by Remilia-sky** [typora/typora-issues#4764]
On MacOS, sometimes the cursor floats when typing in inline-math environment.

A gif for demonstration:

![video](https://user-images.githubusercontent.com/22523872/139592974-9adaac48-ebbe-4d02-b861-cc762e211f49.gif)

I just typed a space and a backspace here, but the cursor gone to the end of the line and then gone back meanwhile.

**Sample Markdown File**
[Untitled.md](https://github.com/typora/typora-issues/files/7449226/Untitled.md)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6

**Typora Version**
 - 0.11.11

**Comment by abnerlee** [comment]
should be fixed in 0.11.16

**Comment by Remilia-sky** [comment]
> should be fixed in 0.11.16

Not completely fixed yet.
Press the leftarrow key at the end of the file:
![tz1e6-8gwcq](https://user-images.githubusercontent.com/22523872/140774719-3abc2ee0-3e41-4506-a42b-55fc373e1f5f.gif)
