### ISSUE TITLE
[Bug] List Indentation Doesn't Work

### ISSUE THREAD

**Issue by sailMW** [typora/typora-issues#4829]
**Describe the bug**

the list indentation doesn't work

**To Reproduce**

1. create a list (just type '1+.+space' , the first line will become the first item of a list, accompanied with an identation, then press 'Enter', the cursor will jump to the next line, creating the second item automatically
2. outdent, either clicking from menu bar or using 'command + [ ' is ok, the second item becomes a usal line accompanied with an outdentation
3. click indent from menu bar or use 'comman + ]', neither of them works
4. this is the bug I met

**Expected behavior**

after the third step, the second line should go back to the state when the first step is done

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1, my mechine is macbook air M1

**Typora Version**
 -  0.11.16  and 0.11.18

the versions before 0.11.16 don't have this problem

**Comment by mjaschen** [comment]
Same behaviour here with:

- Typora 1.0.0
- macOS 12.0.1 @ iMac Late 2019 (Intel)

**Comment by abnerlee** [comment]
fixed in 1.0.2 sorry for the trouble.

**Comment by normren** [comment]
@abnerlee me too

**Comment by sailMW** [comment]
@abnerlee the bug hasn't been fixed completely in 1.0.2, repeating the same procedure the bug still exists.

**Comment by antru** [comment]
At least the fix solved the general indent bug, as described here https://github.com/typora/typora-issues/issues/4838.

**Comment by mightysashiman** [comment]
Indent/outdent features (through tab shortcut or menu) is mess. Indenting from level1 to level2 (at least for an unordered list item) seems to only work if following an item at level1 indenting.
Also : I'm not a markdown expert but does markdown (and then, typora) link various items of a same (un)ordered list through a document? and possible in markdown, how does the user achieve (un)linking between items ?
