### ISSUE TITLE
Problem in additional header row of cross-page table

### ISSUE THREAD

**Issue by kndysfm** [typora/typora-issues#5263]
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

Sometimes, an additional header row of a cross-page table which is generated on export, is broken.
It couldn't be controlled, but it occurs frequently when the table is too big.

**To Reproduce**

Steps to reproduce is not clear because drawn position of table couldn't be controlled explicitly.

1. Make a big table
2. Type text, make the other tables, paste image, or do something to adjust position
3. See error

**Expected behavior**

Always all the tables should be exported without broken header.

**Screenshots / Screencasts**

![image](https://user-images.githubusercontent.com/6650886/169787059-fd359177-a75f-4891-9a9e-5088fe758120.png)

**Sample Markdown File**

[Untitled.md](https://github.com/typora/typora-issues/files/8753271/Untitled.md)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 21H2

**Typora Version**

1.2.5

The problem can occur with the default configuration

**Additional context**

I'm not familiar to web technology, I think it's not problem of the Typora but its integrated renderer.  
And I found that these lines in [github.css](https://github.com/typora/typora-default-themes/blob/master/themes/github.css) are no longer functional.

```cs
    table,
    pre {
        page-break-inside: avoid;
    }
```

Actually, as seen in my screenshot, pages are broken in tables.  
And I modified these lines like...:

```cs
    figure,
    pre {
        page-break-inside: avoid;
    }
```

Because every `table` tag in the exported HTML are wrapped by `figure` tag (I don't know what it is).
Then, the tables in the document got no longer divided by pages.

**Comment by abnerlee** [comment]
fixed in 1.3.6

**Comment by WallZFE** [comment]
The issue still occurs in version 1.8.10 for Windows. Please troubleshoot and fix this. @abnerlee
