### ISSUE TITLE
Chinese characters are not stylized in exported PDF files [bug]

### ISSUE THREAD

**Issue by YimingPan** [typora/typora-issues#553]
Export the following markdown file to PDF:

``` markdown
# 简体中文(Simplified Chinese)

## 简体中文(Simplified Chinese)

### 简体中文(Simplified Chinese)

#### 简体中文(Simplified Chinese)

##### 简体中文(Simplified Chinese)

###### 简体中文(Simplified Chinese)



**简体中文(Simplified Chinese)**

*简体中文(Simplified Chinese)*

<u>简体中文(Simplified Chinese)</u>
```

I get

![image](https://cloud.githubusercontent.com/assets/12478761/23393888/d0b957f4-fdc0-11e6-916b-509bbb151525.png)

The Chinese characters are not stylized as **bold** and _italic_ in the PDF file, but they are in HTML files.

**Comment by abnerlee** [comment]
fixed in new release

**Comment by xingyunjohn1** [comment]
Problem still exists in Win 0.11.8.
The Chinese characters are not stylized as _italic_ in the PDF file.
![image](https://user-images.githubusercontent.com/32031270/158051415-f73ff84e-2558-47cd-8d46-ff1353257990.png)
It seems that the _italic_ YaHei font has not been inserted to the pdf file.
