### ISSUE TITLE
Indentation and Lists Behaves Weird

### ISSUE THREAD

**Issue by yujiewu66** [typora/typora-issues#5687]
Hi,

Describe the Bug:
After turning on the option "indent first line of paragraphs", I start a list and after I wrote the first list item, I hit enter to continue with the second list item, the cursor moves to the place with an indentation after the bullet, as shown in the picture:
![image](https://user-images.githubusercontent.com/83889793/229260115-b32af093-81ba-4841-8716-c73db6220f32.png)
The same issue exists for task list.
![image](https://user-images.githubusercontent.com/83889793/229259930-382db25e-bbfd-4246-b9d7-981e1be01ddf.png)
The ideal and natural movement should be the cursor move to the place right after the bullet point. If I begin typing the the cursor automatically jump back to the right place. It's not a serious issue but it bugs me when I was writing and something just doesn't feel right there, because of the place of the cursor, I automatically want to hit delete to remove the extra place but then that just delete my whole second item and it then looks like this:
![image](https://user-images.githubusercontent.com/83889793/229260486-f098c801-26a3-453d-9f04-9946e5e15209.png)
So if I want to continue my list and add another dash it just became this:
![image](https://user-images.githubusercontent.com/83889793/229260526-8efe32b5-ed6e-46b3-abd0-5354bff1ac00.png)
If instead of adding another dash, I hit delete one more time, the cursor then goes back to the end of the very first line and then the whole process start over again... It really annoys me when I was trying to focus on just typing on my notes, and this is what Typora is suppose to be compared to other apps.

If I turn off the option "indent first line of paragraphs" then this is not an issue but my notes format looks inconsistent with the things I wrote in Latex and start of paragraphs are hard to recognize.

To Reproduce:
- Turn the option:"indent first line of paragraphs."
- Create a list, write a first list item and hit enter, and begin writing a second list item.

OS: 2020 M1 Macbook Air, Ventura 13.0.1
Typora: 1.5.11.

More:
This issue doesn't appear in my Windows 11 laptop installed Typora. 
Also I really enjoyed and loved Typora back when Windows is my main machine. Now I have a Macbook for over a year now, and now mostly the Macbook is my main machine because I also use Goodnotes for handwritten notes a lot. I thought Typora should be the same on both system but it's just slower and more buggy on my Macbook. I don't know why...
Will there be an Electron version of Typora on Mac? I use VS code to write papers in Latex and it works really well on both Mac and Windows. A lot of people use VS code too, so I think another option of Electron based Typora is not that bad an idea to start with.

Thank you so much for your effort!

**Comment by yujiewu66** [comment]
This has been fixed today. I have been using Typora today and it seems normal, the above bug didn't appear any more.

**Comment by nk9** [comment]
I'm still seeing this bug on 1.6.7 and macOS 12.6.6.

<img width="199" alt="Screenshot 2023-06-13 at 10 47 50" src="https://github.com/typora/typora-issues/assets/3646730/e7507406-5d2c-4527-87ae-a6bd7f038ee6">

**Comment by hsandt** [comment]
I have a variant where the second and third level bullets change appearance, but are not indented

![image](https://github.com/typora/typora-issues/assets/1067772/df17f74c-f961-468d-ba43-3491d0f8ae8d)

Sometimes pressing tab at the start of the bullet point would even add an indent instead of changing the bullet.

The source code looks good, except it really added that indent after the hyphen, represented with a red dot.

```
- Princess escapes the dungeon
    - ​	Princess is held in dungeon
    - Princess is held in dungeon
        - Fairy appears
```

![image](https://github.com/typora/typora-issues/assets/1067772/7fb72231-9071-43e0-ae2c-1a709629729b)

**Comment by abnerlee** [comment]
fixed in 1.7.5
