### ISSUE TITLE
Failed to export as PDF. undefined - 1.8.7 on ubuntu

### ISSUE THREAD

**Issue by banikojp** [typora/typora-issues#5958]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
File->Export->PDF->Set Save Location->Save->Error Messages
  "Export failed. Failed to export as PDF. undefined"
  PDF file is not created.

**To Reproduce**
1. Go to 'File'
2. Click on 'Export'
3. Click on 'PDF'

**Expected behavior**
PDF file to be created

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 
 
**Typora Version**
typora_1.8.7_amd64.deb

**Additional context**
In 1.7.6, I was able to export correctly, but after update to 1.8.7, it stopped working.

=== .config/typora.log ===
INFO 2024/1/25 22:26:28  load file [/tmp/Typora/1706189188469-0.11125958933392455.html] for PDF export
ERROR 2024/1/25 22:26:28  Error: ERR_FAILED (-2) loading 'file:///tmp/Typora/1706189188469-0.11125958933392455.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:85498)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:85885)
    at WebContents.emit (node:events:513:28)
    at WebContents.emit (node:domain:489:12) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///tmp/Typora/1706189188469-0.11125958933392455.html'
}

**Comment by abnerlee** [comment]
should be fixed in 1.8.8

**Comment by g4x86** [comment]
Just found a bug in v1.8.8 in Linux: select Help --> My Licenses... in the menu and a dialog popped up showing "Typora Activated" text. However, none of three buttons in the dialog responded to mouse clicks: "Close", "Deactivate" and "View License". This dialog remain on screen even after the main window exits, and there is no way to close this dialog unless I killed corresponding program process at command line directly.

**Comment by g4x86** [comment]
Thanks for the dev team! The latest v1.8.9 on Linux fixed the issue of being unable to close the My Licenses Dialog problem.

However, the v1.8.9 on Windows also has this problem persistent. Hope it can be fixed soon. Many thanks!
