### ISSUE TITLE
Typora does not remember window state on startup

### ISSUE THREAD

**Issue by GreatestFool** [typora/typora-issues#6000]
**Describe the bug**
Previous versions of Typora has allowed the window to remember its state; whether it has been maximized or is in full-screen. Latest does not.

**To Reproduce**
1. Update to the latest version.
2. Open the program.
3. Toggle full-screen.
4. Close the program.
5. Re-open the program.

**Expected behavior**
On completing step 5, it should start in full-screen. Or just maximized, if you did that instead on step 3.

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Enterprise

**Typora Version**
1.8.10

**Additional context**
 This hasn't been an issue before, for me personally, and still worked up until the moment I updated Typora just now. Though I've seen  #1795 and #4932 which are older, and not so dissimilar, so apparently nothing new.

**Comment by Candysad** [comment]
my OS: Windows
Typora Version: 1.8.10
Resolutions of screens:
 - single 1080p (almost full-screen)
 - 1 2k with 1 1080p （oversize to screen）
 - 1 2k with 2 1080p (almost full-screen)

The window of Typora is now fixed to a certain size for each time you open it .

This happended on Windows and the behaviors vary in different resolutions and number of screens.

It's about to be almost full-screen on 1080p screens.
And it could be oversize (even bigger than the screen) on a 2k screen with another 1080p screen connected to PC, 
but almost full-screen on a 2k screen with ohther 2 1080p screens connected.

**Comment by GreatestFool** [comment]
I can expand on this and say that window size varies when opening. I've had it take up some 1/4th of a 4K screen, as well as almost the entirety of it.

Should it be so that the application will not remember its window state going forward, I'd greatly appreciate there being a CLI flag that can be applied to make it start in full-screen. It's a stop-gap, I prefer the old way—if I am to describe it as such—but I think that's fine too.

**Comment by thurrott** [comment]
It's 2024, and this is still broken. Typora does not remember its size or window state (maximized/windowed) on launch in Windows 11.

**Comment by frigvid** [comment]
> It's 2024, and this is still broken. [ . . . ]

I mean, it was opened in 2024, so that's perhaps not the best use of that phrase I've seen.

Though, otherwise, I agree. I'd _really_ like to see this fixed or re-implemented.

**Comment by thurrott** [comment]
> > It's 2024, and this is still broken. [ . . . ]
> 
> I mean, it was opened in 2024, so that's perhaps not the best use of that phrase I've seen.
> 
> Though, otherwise, I agree. I'd _really_ like to see this fixed or re-implemented.

This same bug has been reported over several years.

**Comment by frigvid** [comment]
Fair. I Forgot the older issues.
