### ISSUE TITLE
Crashes when losing focus (Mac)

### ISSUE THREAD

**Issue by avenged110** [typora/typora-issues#619]
v0.9.9.9.3 on OS X 10.9.5
Upon closing all Typora windows but not quitting the app, if focus is changed to another app, Typora will crash. This can be seen in the linked video.
https://youtu.be/4UVaGXlEsdc

According to the crash reports, it's always the same exception type and "application specific information," but can be one of two exception codes. I've included one of each.
[Typora_2017-03-17-171746_MacBook.txt](https://github.com/typora/typora-issues/files/870986/Typora_2017-03-17-171746_MacBook.txt)
[Typora_2017-03-11-160033_MacBook.txt](https://github.com/typora/typora-issues/files/870987/Typora_2017-03-11-160033_MacBook.txt)

There was also another crash that appears to be related, but this was under a different, more normal set of circumstances. I wasn't paying close attention, but with a document open, Typora crashed after switching desktops and Finder coming into focus.
[Typora_2017-03-26-140758_MacBook.txt](https://github.com/typora/typora-issues/files/871037/Typora_2017-03-26-140758_MacBook.txt)

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by avenged110** [comment]
I'm still getting these same crashes on 0.9.9.9.4.
Here's a crash log.
[Typora_2017-03-29-224835_MacBook.txt](https://github.com/typora/typora-issues/files/881166/Typora_2017-03-29-224835_MacBook.txt)

**Comment by abnerlee** [comment]
fixed in new release
