### ISSUE TITLE
Linux Spell check failed to work

### ISSUE THREAD

**Issue by bluelancer** [typora/typora-issues#640]
Dear all,

It might be a problem that my typora_0.9.25-1 fails to work on Spellcheck, I have ticked the enable spell check in preference while this makes  no difference.

B.R.
Yifei
![screenshot from 2017-04-11 10 31 52](https://cloud.githubusercontent.com/assets/16851833/24899860/215f3276-1ea2-11e7-9652-b37c9f72e9f2.png)

**Comment by abnerlee** [comment]
Fixed in new release

**Comment by bluelancer** [comment]
Dear abnerlee,

I tried the now release  typora (0.9.27-1), while the problem still happens:

![screenshot from 2017-04-19 13 07 21](https://cloud.githubusercontent.com/assets/16851833/25177159/326ea2f8-2501-11e7-9938-632bfcc880f5.png)

B.R.
Yifei Jin

**Comment by abnerlee** [comment]
Have you enable it in preference panel?

**Comment by bluelancer** [comment]
Yes I did.
![screenshot from 2017-04-24 13 55 12](https://cloud.githubusercontent.com/assets/16851833/25335991/bbd96a26-28f5-11e7-8a7b-cb45500ca97a.png)

**Comment by bluelancer** [comment]
Dear all,

The problem continues in the new release.

B.R.
Yifei

**Comment by orschiro** [comment]
Maybe related?

https://github.com/typora/typora-issues/issues/476

**Comment by darnu** [comment]
I can confirm that the problem still exists under version 0.9.29(beta) for Ubuntu 14.04.

**Comment by samirelanduk** [comment]
And 0.9.31 beta on Ubuntu 16.04 - same issue as described above

**Comment by James-Firth** [comment]
After updating to 0.9.38 beta on Ubuntu 16.04 I also still do not see the underline for spellcheck after enabling it in preferences.

**Comment by bramvermeer** [comment]
I had the same issue in 0.9.38 beta on Ubuntu 16.04 with the Ubuntu system language set to Dutch (my native language). When I changed the system language from Dutch into English, the issue was solved for me. I could see the underline for non-English words. Maybe it would be better to make this independent from system settings. What´s more, it would be great if the spell check dictionaries could be selected in Typora´s preference menu, also for other languages.

**Comment by samirelanduk** [comment]
Still an issue on 0.9.44b (Ubuntu 16.04). It almost renders the whole application fairly useless as anything written on the Ubuntu application has to be opened on the Mac for a spell check.

**Comment by th-we** [comment]
It would be better to make the spell checking dependent on the language chosen in the settings, not the system language.

![grafik](https://user-images.githubusercontent.com/1147152/42628522-a726edf4-85d0-11e8-95b4-5465a9c181fb.png)

(Ideally, the language should be selectable independent of both, but having at least English spell checking on a non-English system would already be a great improvement.)

**Comment by xorb0ss** [comment]
I'm also having the same problem under 0.9.53

**Comment by cafeduke** [comment]
I am using Typora 0.9.58 (beta) on Ubuntu 18.04. The spell check was not working. 
1. "Enable spell check" is checked.
2. In my Ubuntu, under  Settings > 'Region and Language' the Language is set to 'English (United States)' and the 'Formats' is set to 'India'

I find that `/usr/share/typora/resources/app/node_modules/spellchecker/lib/spellchecker.js` uses `process.env.LANG` to determine the language. In my case, it was `en_IN`

```bash
$ cat test.js
console.log(process.env.LANG)

$ node test.js
en_IN
```

I copied the `en_US` files to `en_IN` and this fixed the spell issue that was driving me crazy.
```bash
cd /usr/share/typora/resources/app/node_modules/spellchecker/vendor/hunspell_dictionaries
sudo cp en_US.aff en_IN.aff
sudo cp en_US.dic en_IN.dic
```
Thanks to the Typora team for the **awesome** markdown editor !!

**Comment by vkbo** [comment]
As expected, the above recipe also works for en_GB. Maybe this should be added as a HOWTO for non US spelling? I simply ran `sudo cp /usr/share/hunspell/en_GB.* .` in the above mentioned folder, and I have UK spell check.

Is there any reason why Typora cannot just use the hunspell dictionaries installed?

**Comment by trzczy** [comment]
Does the "Learn Spelling" work in your Typora? I mine not. I cannot add the word "Nginx" eg. etc. Spell checking works well since I turned the language to en_US but Learn Spelling. I have Debian 9 and Typora 0.9.58(beta)

**Comment by abnerlee** [comment]
Should be fixed in new release

**Comment by max-k** [comment]
Hi,

I'm sorry but I try to use french spellchecking on Linux and it still doesn't work.

I tried to download fr dictionaries from https://dict.typora.io/ and put them in ~/.config/Typora/dictionaries/ as fr_FR.dic and fr_FR.aff.

I tried to directoly put the downloaded fr directory in ~/.config/Typora/dictionaries and i didn't work.

I tried to symlink all french dictionaries from hunspell using the following command:
```sudo ln -s /usr/share/hunspell/fr* /usr/share/typora/resources/app/node_modules/spellchecker/vendor/hunspell_dictionaries/```
But it also didn't work.

Just to be sure, I also tried to symlink them to the local dictionaries directory but I didn't work.
```sudo ln -s /usr/share/hunspell/fr* /home/my_username/.config/Typora/dictionaries/```

Do you have another idea ?

**Comment by DroWnThePoor** [comment]
I'm now on v0.9.72 and can confirm spellcheck is STILL not working.
Not complaining, as this is a truly great markdown editor, just trying to draw attention to this issue.

**Comment by TimothyHills** [comment]
Linux Mint 19.3 Cinnamon. Typora version 0.9.98. I can only have EN-US not EN-GB. If I switch it to auto detect, each time I launch Typora I have to re-download the en_GB-ise Hunspell Dictionary, and it works till the end of the session. If I switch manually to EN-US then it all works fine, except I have to spell like an American. :-( 

If it helps I noticed there is a Dictionaries folder and a dictionaries folder. I'm wondering whether there is a case sensitive typo in play, being Linux.

I plan to do the rename thingy with the files, fingers crossed.

**Comment by rpopov** [comment]
Oracle Linux 8.3, Typora version 0.9.98. Activating Spell Check for EN_US starts downloading the dictionary and never stops. 
I disabled the Spell  Check, restarted, and activated it. The Spell Check worked. Repeated. Worked ;-)
Opening the same document in two windows, fails the spell check unconditionally.
Opening more than one documents may fail the Spell Check.

**Comment by panos-stavrianos** [comment]
I got pretty much the same behavior with Timothy, on `Ubuntu 20.04` and `Typora version 0.11.8`
In my case when i download the language (Greek) the spelling is working but no suggestions are provided. 
When i restart the app i have to re download the dictionary.
I try the manual download and linking with no luck
On `EN-US` it works just fine

**Comment by spxak1** [comment]
I can confirm 0.11.16 spelcheck in Greek doesn't work at all.

Setting manually the language to Greek prompts to download the dictionary files, ```el.aff``` and ```el.dic```, and after that all greek words are underlined as misspelled (no suggestions).

Copying the dictionaries (```el_GR.aff``` and ```el_GR.dic```) from ```/usr/share/hunspell/``` to ```/home/user/.config/Typora/typora-dictionaries``` makes no difference unless they're renamed to ```el.aff``` and ```el.dic``` and the only change is that Typora then (upon restart) just won't offer to download them again, but the same behaviour (all words marked misspelled) takes place.

English UK (```en_GB```) worked properly though. Typora offered to download the files, it did, it worked. Auto language detection also works.

Thank you.

**Comment by abnerlee** [comment]
@spxak1 Hi, possible to provide a small Greek sample that only few words are misspelled for us to test?

**Comment by panos-stavrianos** [comment]
> @spxak1 Hi, possible to provide a small Greek sample that only few words are misspelled for us to test?
Here some tests
```
δοκιμη   -> δοκιμή
δοκιμι    -> δοκιμή
δοκειμή -> δοκιμή
παιζω    -> παίζω
παίζο    -> παίζω
πεζος    -> πεζός 
```

**Comment by spxak1** [comment]
> @spxak1 Hi, possible to provide a small Greek sample that only few words are misspelled for us to test?

![image](https://user-images.githubusercontent.com/29977030/140653091-82279575-bb33-4cca-b1ae-c5dea6547681.png)

Please see this short video of the issue if it helps more: https://streamable.com/zipvak

**Comment by abnerlee** [comment]
I can reproduce this for Greek spellcheck.

Seems a issue with the dictionary, we would fix in next version up.

For now, for Greek spellchecker, please download el dict from https://github.com/wooorm/dictionaries/tree/main/dictionaries/el
rename index.aff and index.dic to el.aff, index.dic and put them into /home/user/.config/Typora/typora-dictionaries

**Comment by spxak1** [comment]
> I can reproduce this for Greek spellcheck.
> 
> Seems current hunspell implementation in typora cannot read the file successfully (or caused by wrong encoding?), we would update the dict and remove old one in next version up.
> 
> For now, for Greek spellchecker, please download el dict from https://github.com/wooorm/dictionaries/tree/main/dictionaries/el rename index.aff and index.dic to el.aff, index.dic and put them into /home/user/.config/Typora/typora-dictionaries

Thanks for this. I followed the workaround suggested, deleted any el.* files in typora-dictionaries, downloaded the suggested files, renamed them and placed them in the correct location. Typora sees them (as it does not offer me to download the dictionaries) but I get the same behaviour, i.e all words underlined, no suggestions.

I will keep trying if this is an issue on my end, but this is a different box to the one I used for the screengrab above, (same OS and updates though).

Thanks again fro all this effort.

**Comment by spxak1** [comment]
I can confirm that this issue is now **fixed** with version 0.11.16-1

Remove all el.* files from ```typora-dictionaries```, start typing in greek, select spell check, install as prompted, it works.

Thank you very much!
