### ISSUE TITLE
[bug] lose edit position when switch between tabs using shortcuts

### ISSUE THREAD

**Issue by die4live** [typora/typora-issues#901]
The cursor will jump to top or bottom of the whole text (and sometime other places) when use keyboard (Control+Tab/Control+Shift+Tab).

version 0.9.9.10.6 of macOS 10.12.6

**Comment by abnerlee** [comment]
should be fixed in 0.9.9.10.8, please try update!

**Comment by die4live** [comment]
@abnerlee 0.9.9.10.6 is the latest version as this issue was post, and it still exists for the 0.9.9.10.8.

more details: cursor will jump to head of all text when you use `ctrl-tab` and tail for `ctrl-shift-tab`

**Comment by haodong** [comment]
@abnerlee This problem still exist on v0.9.9.19.4.
