### ISSUE TITLE
Can't back to the main screen when remove the expand the screen

### ISSUE THREAD

**Issue by yangmqglobe** [typora/typora-issues#904]
When I use typora in the expand  screen(another monitor) in windows 10 once, it will stick in that screen even if I remove the monitor from my laptop, and I open typroa, I can find it in the task bar, but it just not show in the screen. I found that other programs will back to the main screen when I remove the expand screen, but typora not, is this a bug?

**Comment by abnerlee** [comment]
should be fixed in the new release

**Comment by yangmqglobe** [comment]
this bug still occur in 0.9.41(beta) on win10, I found that Postman have this bug, too. It is a bug from Electron?

**Comment by abnerlee** [comment]
@yangmqglobe How about Chrome?

**Comment by yangmqglobe** [comment]
Chrome will return to main screen immediately when I remove the expand screen.
